[tool.poetry]
name = "llm-adapters"
version = "8.14.1"
description = "Adapters as API gateways to Different LLM Models"
authors = ["Martian team <team@withmartian.com>"]
readme = "README.md"
packages = [{ include = "llm_adapters", from = "." }]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.11.7"
anthropic = "^0.58.2"
openai = "^1.97.0"
cohere = "^5.16.1"
brotli = "^1.1.0"
httpx = "^0.28.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.4.1"
pytest-dotenv = "^0.5.2"
pytest-asyncio = "^1.1.0"
pytest-recording = "^0.13.4"
mypy = "^1.17.0"
vcrpy = "^7.0.0"
ruff = "^0.12.4"
pytest-xdist = "^3.8.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^4.2.0"
