import os
import re

from llm_adapters import general_utils

from llm_adapters.abstract_adapters import (
    ApiKeyAdapterMixin,
    Adapter,
    BaseAdapter,
    OpenAISDKChatAdapter,
    SDKChatAdapter,
    ProviderAdapterMixin,
)
from llm_adapters.types import (
    NotGiven,
    NOT_GIVEN,
    Completion,
    ChatCompletion,
    ChatCompletionChunk,
    ChatCompletionMessageParam,
    Query,
    Body,
    Headers,
    ChatModel,
    ChatCompletionAudioParam,
    FunctionCall,
    FunctionCreate,
    ChatCompletionModality,
    ChatCompletionPredictionContentParam,
    ResponseFormat,
    ChatCompletionReasoningEffort,
    ChatCompletionStreamOptionsParam,
    ChatCompletionToolChoiceOptionParam,
    ChatCompletionToolParam,
    ChatCompletionCreateKwargs,
    CompletionCreateKwargs,
    AdapterException,
    AdapterRateLimitException,
    Provider,
    Vendor,
    ConversationRole,
    AdapterFinishReason,
    ContentType,
    Cost,
    ModelProperties,
    Model,
    AdapterChatCompletion,
    AdapterStreamChatCompletion,
    AdapterStreamSyncChatCompletion,
    AdapterStreamAsyncChatCompletion,
    AdapterChatCompletionChunk,
    AdapterCompletion,
    AdapterCompletionChunk,
    AdapterStreamCompletion,
    AdapterStreamSyncCompletion,
    AdapterStreamAsyncCompletion,
    AdapterModelNotFoundException,
    ChatCompletionCreateArgs,
    CompletionCreateArgs,
    ChatCompletionUserMessageParam,
    ChoiceChunk,
    ChoiceDelta,
    ChatCompletionMessageToolCall,
    Choice,
    ChatCompletionMessage,
    CompletionUsage,
    FunctionToolCall,
    FileObject,
    FilePurpose,
    Metadata,
    Batch,
    HttpxBinaryResponseContent,
    SyncCursorPage,
    AsyncCursorPage,
    AsyncPaginator,
    # Deprecated
    Turn,
    FunctionOutputTurn,
    ToolOutputTurn,
    ToolsCallTurn,
    ImageDetailsType,
    VisionImageDetails,
    TextContentEntry,
    ImageContentEntry,
    ContentTurn,
    TurnType,
    Conversation,
    Prompt,
    AdapterResponse,
    AdapterStreamResponse,
)
from llm_adapters.adapter_factory import AdapterFactory
from llm_adapters.client import OpenAI, AsyncOpenAI
from llm_adapters.custom_sdk_chat_provider_adapter import (
    CustomOpenAISDKChatProviderAdapter,
    CustomAISDKChatProviderAdapter,
)

# Get version from pyproject.toml
try:
    # Find the project root directory
    _root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    _pyproject_path = os.path.join(_root_dir, "pyproject.toml")

    # Read the version from pyproject.toml using regex
    with open(_pyproject_path, "r", encoding="utf-8") as f:
        _content = f.read()
        _version_match = re.search(r'version\s*=\s*["\']([^"\']+)["\']', _content)
        if _version_match:
            __version__ = _version_match.group(1)
        else:
            __version__ = "unknown"  # Current version as fallback
except (FileNotFoundError, Exception):
    __version__ = "unknown"  # Current version as fallback

__all__ = [
    "__version__",
    "OpenAI",
    "AsyncOpenAI",
    "general_utils",
    "ApiKeyAdapterMixin",
    "Adapter",
    "BaseAdapter",
    "OpenAISDKChatAdapter",
    "SDKChatAdapter",
    "ProviderAdapterMixin",
    "TurnType",
    "ContentTurn",
    "FunctionOutputTurn",
    "ToolOutputTurn",
    "ToolsCallTurn",
    "FunctionCallTurn",
    "Cost",
    "Model",
    "AdapterChatCompletion",
    "AdapterStreamChatCompletion",
    "AdapterStreamSyncChatCompletion",
    "AdapterStreamAsyncChatCompletion",
    "AdapterChatCompletionChunk",
    "AdapterException",
    "AdapterRateLimitException",
    "AdapterModelNotFoundException",
    "Prompt",
    "AdapterResponse",
    "AdapterStreamResponse",
    "AdapterCompletion",
    "AdapterCompletionChunk",
    "AdapterStreamCompletion",
    "AdapterStreamSyncCompletion",
    "AdapterStreamAsyncCompletion",
    "Provider",
    "Vendor",
    "ConversationRole",
    "AdapterFinishReason",
    "VisionImageDetails",
    "TextContentEntry",
    "ImageContentEntry",
    "ContentType",
    "ModelProperties",
    "AdapterFactory",
    "CustomOpenAISDKChatProviderAdapter",
    "CustomAISDKChatProviderAdapter",
    "NotGiven",
    "NOT_GIVEN",
    "Completion",
    "ChatCompletion",
    "ChatCompletionChunk",
    "ChatCompletionMessageParam",
    "Query",
    "Body",
    "Headers",
    "ChatModel",
    "ChatCompletionAudioParam",
    "FunctionCall",
    "FunctionCreate",
    "ChatCompletionModality",
    "ChatCompletionPredictionContentParam",
    "ResponseFormat",
    "ChatCompletionReasoningEffort",
    "ChatCompletionStreamOptionsParam",
    "ChatCompletionToolChoiceOptionParam",
    "ChatCompletionToolParam",
    "ChatCompletionCreateKwargs",
    "CompletionCreateKwargs",
    "ChatCompletionCreateArgs",
    "CompletionCreateArgs",
    "ChatCompletionUserMessageParam",
    "ChoiceChunk",
    "ChoiceDelta",
    "ChatCompletionMessageToolCall",
    "Choice",
    "ChatCompletionMessage",
    "CompletionUsage",
    "FunctionToolCall",
    "FileObject",
    "FilePurpose",
    "Metadata",
    "Batch",
    "HttpxBinaryResponseContent",
    "SyncCursorPage",
    "AsyncCursorPage",
    "AsyncPaginator",
    # Deprecated
    "Turn",
    "ImageDetailsType",
    "Conversation",
]
