name: Enforce Version Bump

on:
  pull_request:
    branches:
      - main

jobs:
  check-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we fetch all history for version comparison

      - name: Get previous version
        id: old_version
        run: echo "OLD_VERSION=$(git show origin/main:pyproject.toml | grep -E '^version\s*=\s*' | cut -d '"' -f2)" >> $GITHUB_ENV

      - name: Get new version
        id: new_version
        run: echo "NEW_VERSION=$(grep -E '^version\s*=\s*' pyproject.toml | cut -d '"' -f2)" >> $GITHUB_ENV

      - name: Compare versions
        run: |
          if [ "$NEW_VERSION" == "$OLD_VERSION" ]; then
            echo "Version was not bumped! Current: $NEW_VERSION, Expected new version."
            exit 1
          else
            echo "Version updated: $OLD_VERSION -> $NEW_VERSION"
          fi
